require "./abstract_spin_box"
require "../mixin/sectioned_field"

module Crysterm
  class Widget
    # Combined date+time entry field, modeled after Qt's `QDateTimeEdit`.
    #
    # Shows `YYYY-MM-DD HH:MM:SS` with one *section* highlighted, joining the
    # behavior of `DateEdit` and `TimeEdit`: Left/Right move between the six
    # sections, Up/Down (or the mouse wheel over a section) step it — wrapping
    # within the section's own range without carrying — and a click selects the
    # section under the pointer. Emits `Event::DateChanged` (carrying the `Time`)
    # on every change.
    #
    # Like Qt's default `QDateTimeEdit` (`calendarPopup == false`), it is edited
    # in place with no drop-down. The shared section machinery lives in
    # `Mixin::SectionedField`.
    #
    # <!-- widget-examples:capture v1 -->
    # ![DateTimeEdit screenshot](../../tests/widget/date_time_edit/date_time_edit.5s.apng)
    # <!-- /widget-examples:capture -->
    class DateTimeEdit < AbstractSpinBox
      include Mixin::SectionedField

      @datetime : Time
      # `@section`: 0=year 1=month 2=day 3=hour 4=minute 5=second.

      # Whether the seconds section is shown and editable.
      property? show_seconds : Bool = true

      # Re-wraps the generated setter: toggling seconds off while the seconds
      # section (index 5) is selected re-clamps `@section` into range (0..4)
      # instead of pointing at a section that no longer renders.
      def show_seconds=(value : Bool) : Bool
        return value if value == @show_seconds
        @show_seconds = value
        @section = @section.clamp(0, section_count - 1)
        update_content
        update!
        value
      end

      def initialize(date_time : Time? = nil, show_seconds = true, **input)
        @datetime = (date_time || Mixin::SectionedField.default_today)
          .clamp(@minimum_date_time, @maximum_date_time)
        @show_seconds = show_seconds

        super **{keys: true}.merge(input)
        @parse_tags = true

        handle Crysterm::Event::KeyPress
        setup_section_mouse

        update_content
      end

      # ---- Value + bounds -------------------------------------------------

      # Earliest/latest values this edit accepts (Qt's
      # `QDateTimeEdit#minimumDateTime`/`maximumDateTime`), defaulting to the
      # same span `Widget::Calendar` uses. Spelled `*_date_time` rather than
      # `Calendar`'s `*_date` because the bound here really is a full instant:
      # the edit's own value has a time-of-day, so a date-only bound could not
      # express "up to 09:00 today".
      @minimum_date_time : Time = Time.utc(1752, 9, 14)
      @maximum_date_time : Time = Time.utc(9999, 12, 31, 23, 59, 59)

      def minimum_date_time : Time
        @minimum_date_time
      end

      # As in `Calendar#minimum_date=` (and Qt): a new minimum above the current
      # maximum carries the maximum up with it rather than inverting the range.
      def minimum_date_time=(value : Time) : Time
        set_date_time_range value, Math.max(value, @maximum_date_time)
        @minimum_date_time
      end

      def maximum_date_time : Time
        @maximum_date_time
      end

      # :ditto: — a new maximum below the current minimum carries the minimum
      # down with it.
      def maximum_date_time=(value : Time) : Time
        set_date_time_range Math.min(@minimum_date_time, value), value
        @maximum_date_time
      end

      # Sets both bounds at once (Qt's `setDateTimeRange`), re-clamping the
      # current value into the new range. Mirrors `Calendar#set_date_range`,
      # including its swap-on-crossing.
      def set_date_time_range(min : Time, max : Time) : Nil
        min, max = max, min if min > max
        @minimum_date_time = min
        @maximum_date_time = max
        self.date_time = @datetime
        update_content
        update!
      end

      # The edited instant (Qt's `QDateTimeEdit#dateTime`).
      def date_time : Time
        @datetime
      end

      # Sets the edited instant, clamped into
      # `[#minimum_date_time, #maximum_date_time]`. Every mutation — the section
      # steppers, `#date=`, `#time=` — funnels through here, so no path can
      # leave a value outside the bounds. Written out rather than generated by
      # `section_value` because that macro has no clamping step.
      def date_time=(value : Time) : Time
        v = value.clamp(@minimum_date_time, @maximum_date_time)
        return @datetime if v == @datetime
        @datetime = v
        commit_value @datetime
        @datetime
      end

      # The date part, at the beginning of its day (Qt's `QDateTimeEdit#date`);
      # the same type `DateEdit#date` answers with.
      def date : Time
        @datetime.at_beginning_of_day
      end

      # Replaces the date part, keeping the current time of day (Qt's
      # `setDate`). Clamped through `#date_time=`.
      def date=(value : Time) : Time
        self.date_time = value.at_beginning_of_day + @datetime.time_of_day
        date
      end

      # The time of day (Qt's `QDateTimeEdit#time`, whose `QTime` has no
      # Crystal counterpart — a `Time::Span` since midnight is the idiomatic
      # stand-in, and unlike a full `Time` it cannot be confused with
      # `#date_time`).
      def time : Time::Span
        @datetime.time_of_day
      end

      # Replaces the time of day, keeping the current date (Qt's `setTime`).
      # Clamped through `#date_time=`.
      def time=(value : Time::Span) : Time::Span
        self.date_time = @datetime.at_beginning_of_day + value
        time
      end

      # :ditto: — convenience overload taking *value*'s time of day, so a
      # `Time` from elsewhere can be handed straight over.
      def time=(value : Time) : Time::Span
        self.time = value.time_of_day
      end

      private def section_count : Int32
        show_seconds? ? 6 : 5
      end

      # Inclusive section end-columns for `YYYY-MM-DD HH:MM:SS` (19 cols) and
      # `YYYY-MM-DD HH:MM` (16 cols): YYYY+`-` → 4, MM → 7, DD+` ` → 10, HH → 13,
      # MM → 16, SS → 18. Hoisted so a mouse press/wheel doesn't rebuild the array.
      SECTION_ENDS_SECONDS    = [4, 7, 10, 13, 16, 18]
      SECTION_ENDS_NO_SECONDS = [4, 7, 10, 13, 15]

      # Maps an absolute x to a section index; `nil` past the text.
      private def section_at(x : Int32) : Int32?
        section_from_columns x, show_seconds? ? SECTION_ENDS_SECONDS : SECTION_ENDS_NO_SECONDS
      end

      private def update_content : Nil
        t = @datetime
        parts = [
          t.year.to_s.rjust(4, '0'),
          t.month.to_s.rjust(2, '0'),
          t.day.to_s.rjust(2, '0'),
          t.hour.to_s.rjust(2, '0'),
          t.minute.to_s.rjust(2, '0'),
          t.second.to_s.rjust(2, '0'),
        ]
        parts = highlight_part parts

        date = "#{parts[0]}-#{parts[1]}-#{parts[2]}"
        time = show_seconds? ? "#{parts[3]}:#{parts[4]}:#{parts[5]}" : "#{parts[3]}:#{parts[4]}"
        set_content "#{date} #{time}"
      end

      # Steps the active section by *delta* (its `@section` is the component index
      # directly), wrapping within its own range; day clamped to the target month.
      private def step(delta : Int32) : Nil
        self.date_time = step_time_field @datetime, @section, delta
      end

      def handle_key_press(e)
        handle_section_key e
      end
    end
  end
end
