# IMPRESSIVE DEMO: an image rendered as ASCII-art.
#
# The same `Widget::ANSIImage`, but with `ascii: true`: each cell becomes a
# luminance-picked glyph (libcaca ramp) tinted with the pixel's color — classic
# ASCII art, generated by the framework. Here: a portrait of Albert Einstein.
#
# Fills the standard 80x15 window.

require "../../src/crysterm"

include Crysterm

s = Screen.new title: "ASCII image"
s.show_fps = nil

iw = s.awidth
ih = s.aheight - 1

Widget::ANSIImage.new \
  parent: s, top: 1, left: 0, width: iw, height: ih,
  ascii: true, animate: false,
  file: "#{__DIR__}/../../screenshots/matterhorn.png"

Widget::Box.new \
  parent: s, top: 0, left: 0, width: "100%", height: 1,
  content: "{center}ASCII-art rendering (ascii: true)  ·  the Matterhorn{/center}",
  parse_tags: true, style: Style.new(fg: "white", bg: "#181818")

s.on(Event::KeyPress) do |e|
  if e.char == 'q' || e.key == Tput::Key::CtrlQ
    s.destroy
    exit
  end
end

s.render
s.exec
