# Demo: all UI state lives in signals. A timer changes it each tick and the
# widgets update themselves — no render call is ever written by hand. The look
# comes entirely from a loaded Breeze theme, swapped live between light and dark.
#
# Keys:  p +5   m toggle mode   t toggle theme   b batch   a add   c clear   q quit

require "../../src/crysterm"

include Crysterm

# A Box with a signal-backed `status` property (generated by reactive_property).
class StatusLabel < Widget::Box
  # ameba:disable Lint/UselessAssign
  reactive_property status : String = "idle"
end

s = Window.new title: "Crysterm — Reactive"

THEME_DIR = File.join __DIR__, "..", "..", "data", "css"

# --- state -------------------------------------------------------------------

count = Reactive::Signal.new 0
mode = Reactive::Signal.new true    # picks which value the info panel shows
theme = Reactive::Signal.new "dark" # names the stylesheet to load

# Values derived from count, recomputed only when count changes.
doubled = Reactive::Computed(Int32).new { count.value * 2 }
percent = Reactive::Computed(Int32).new { count.value % 101 }

# List contents; individual rows are patched as this changes.
log = Reactive::ObservableList(String).new ["log started"]

# --- widgets --------------------------------------------------------------
#
# No fixed positions and no colors of their own. Nested layouts place and size
# everything; the loaded theme paints it. Screen splits into a header row and a
# body; the body splits into a left column of panels and the log on the right.

root = Widget::Box.new parent: s, width: "100%", height: "100%",
  layout: Layout::VBox.new, overflow: :ignore

Widget::Box.new parent: root, height: 1, parse_tags: true,
  content: "{center}p:+5  m:mode  t:theme  b:batch  a:add  c:clear  q:quit{/center}"

body = Widget::Box.new parent: root, layout: Layout::HBox.new(spacing: 1), overflow: :ignore

left = Widget::Box.new parent: body, width: 30, layout: Layout::VBox.new, overflow: :ignore
count_box = Widget::Box.new parent: left, height: 3, parse_tags: true
doubled_box = Widget::Box.new parent: left, height: 3, parse_tags: true
progress = Widget::Box.new parent: left, height: 3, parse_tags: true
status = StatusLabel.new parent: left, height: 3, parse_tags: true
info = Widget::Box.new parent: left, height: 3, parse_tags: true
footer = Widget::Box.new parent: left, height: 1

log_list = Widget::List.new parent: body

# --- wiring ------------------------------------------------------------------

# Show count; re-runs whenever count changes.
Reactive.bind(count_box, count) { count_box.content = "{center}Count: #{count.value}{/center}" }

# Show the derived value; fires only when doubled's result actually changes.
Reactive.bind(doubled_box, doubled) { doubled_box.content = "{center}Doubled: #{doubled.value}{/center}" }

# Draw a text bar from the derived percentage.
Reactive.bind(progress, percent) do
  n = percent.value
  fill = n * 20 // 100
  progress.content = "{center}#{"█" * fill}#{"░" * (20 - fill)} #{n}%{/center}"
end

# Set the status property from count, then show it. The effect finds count as a
# dependency on its own.
Reactive.effect(status) { status.status = count.value.even? ? "EVEN #{count.value}" : "ODD #{count.value}" }
Reactive.bind(status, status.status_signal) { status.content = "{center}Parity: #{status.status}{/center}" }

# Reads count when mode is true, doubled when false. Flipping mode changes which
# value this depends on — the dependency set is rebuilt on each run.
Reactive.effect(info) do
  info.content = "{center}#{mode.value ? "Mode A · count=#{count.value}" : "Mode B · doubled=#{doubled.value}"}{/center}"
end

# Load the Breeze stylesheet for the current theme; reloads when theme flips.
Reactive.effect do
  s.load_stylesheet File.join(THEME_DIR, theme.value == "dark" ? "breeze-dark.qss" : "breeze-light.qss")
  s.render
end

# Reads count normally but theme through untracked, so flipping the theme does
# not re-run this — the label catches up on the next count tick.
Reactive.effect(footer) do
  footer.content = " count=#{count.value}  theme=#{Reactive.untracked { theme.value }}"
end

# Keep the list rows in step with the collection, one row per change.
Reactive.bind_items(log_list, log, &.itself)

# --- driver: one timer exercises everything with no key press ----------------

i = 0
s.every(0.2.seconds) do
  count.value += 1
  count.value = 0 if count.value > 999
  log << "tick #{i} (count=#{count.value})" if i % 3 == 0 # add a row
  log.shift if log.size > 12                              # drop the oldest
  mode.update { |v| !v } if i % 10 == 0                   # swap the info panel's source
  theme.update { |v| v == "dark" ? "light" : "dark" } if i % 15 == 0
  if i > 0 && i % 25 == 0
    Reactive.batch do # two writes, dependents run once
      count.value += 50
      mode.update { |v| !v }
    end
  end
  i += 1
end

s.on(Crysterm::Event::KeyPress) do |e|
  case e.char
  when 'p' then count.value += 5
  when 'm' then mode.update { |v| !v }
  when 't' then theme.update { |v| v == "dark" ? "light" : "dark" }
  when 'b' then Reactive.batch { count.value += 100; mode.update { |v| !v } }
  when 'a' then log << "manual entry ##{log.size}"
  when 'c' then log.clear
  end
end

s.exec
