name: CI

on:
  push:
  pull_request:

jobs:
  spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
      - name: Install packages
        run: sudo apt-get update -y && sudo apt-get install -y libunibilium-dev
      - name: Install dependencies
        run: shards install --ignore-crystal-version
      - name: Run specs
        run: crystal spec
